### ISSUE TITLE
Time-line report shows same issue multiple times 

### ISSUE THREAD

**Issue by ramaramesh11** [bitovi/jira-timeline-report#78]
Time-line report shows same issue multiple times if "Load all children of JQL" check box is selected. 
URL: https://timeline-report.bitovi-jira.com/?jql=issuekey+in+portfolioChildIssuesOf%28%22SFGPP-1%22%29+and+issueType+in+%28Milestone%2C+Initiative%2C+Epic%29&primaryReportType=due&loadChildren=true
<img width="881" alt="image002" src="https://github.com/bitovi/jira-timeline-report/assets/65302581/1ae00d12-e0e3-420c-afed-6b8269a3713f">
<img width="569" alt="image001 (1)" src="https://github.com/bitovi/jira-timeline-report/assets/65302581/20eae31a-aac9-42f2-9106-c10339188d40">

**Comment by justinbmeyer** [comment]
This is fixed in staging.  I should be making a release soon.  If you see this again, let us know.
